[2023-08-16T20:02:10.266+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-13T00:00:00+00:00 [queued]>
[2023-08-16T20:02:10.275+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-13T00:00:00+00:00 [queued]>
[2023-08-16T20:02:10.276+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T20:02:10.277+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-08-16T20:02:10.278+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T20:02:10.288+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_credentials> on 2023-08-13 00:00:00+00:00
[2023-08-16T20:02:10.294+0000] {standard_task_runner.py:55} INFO - Started process 2204 to run task
[2023-08-16T20:02:10.299+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'random_user_v1', 'extract_relevant_credentials', 'scheduled__2023-08-13T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/random_user_etl.py', '--cfg-path', '/tmp/tmpv7ucrthb']
[2023-08-16T20:02:10.301+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask extract_relevant_credentials
[2023-08-16T20:02:10.363+0000] {task_command.py:389} INFO - Running <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-13T00:00:00+00:00 [running]> on host c0eab1525b89
[2023-08-16T20:02:10.460+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mujjeeb
AIRFLOW_CTX_DAG_ID=random_user_v1
AIRFLOW_CTX_TASK_ID=extract_relevant_credentials
AIRFLOW_CTX_EXECUTION_DATE=2023-08-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-13T00:00:00+00:00
[2023-08-16T20:02:10.464+0000] {python.py:177} INFO - Done. Returned value was: (['احسان', 'Kenan', 'Clyde', 'Neil', 'Brendan', 'Brad', 'محمد', 'Efe', 'Gayathri', 'Florijn'], ['جعفری', 'Sarıoğlu', 'Day', 'Cox', 'Fitzsimmons', 'Ferguson', 'زارعی', 'Düşenkalkar', 'Kamath', 'Alkemade'], ['male', 'male', 'male', 'male', 'male', 'male', 'male', 'male', 'female', 'male'], ['hsn.jaafry@example.com', 'kenan.sarioglu@example.com', 'clyde.day@example.com', 'neil.cox@example.com', 'brendan.fitzsimmons@example.com', 'brad.ferguson@example.com', 'mhmd.zraay@example.com', 'efe.dusenkalkar@example.com', 'gayathri.kamath@example.com', 'florijn.alkemade@example.com'], [datetime.date(1963, 5, 9), datetime.date(1983, 8, 19), datetime.date(1986, 9, 20), datetime.date(1989, 1, 19), datetime.date(1990, 8, 6), datetime.date(1949, 5, 29), datetime.date(1957, 9, 16), datetime.date(1950, 10, 24), datetime.date(1959, 6, 21), datetime.date(1956, 5, 13)], ['Iran', 'Turkey', 'Ireland', 'United Kingdom', 'Ireland', 'Australia', 'Iran', 'Turkey', 'India', 'Netherlands'], ['House 4163, ایران', 'House 6933, Necatibey Cd', 'House 280, Mill Lane', 'House 4532, Main Street', 'House 8366, Jones Road', 'House 8830, White Oak Dr', 'House 1988, دکتر لواسانی', 'House 9583, Atatürk Sk', 'House 6292, Tripolia Bazar', 'House 1064, Cellenkampstraat'], ['اراک', 'Van', 'Celbridge', 'Belfast', 'Athy', 'Rockhampton', 'کرمان', 'Ardahan', 'Howrah', 'Baneheide'], ['سمنان', 'Ağrı', 'Roscommon', 'West Midlands', 'Cork City', 'Western Australia', 'یزد', 'Tunceli', 'Tripura', 'Zeeland'], [58681, 29126, 62398, 'IJ0M 5RR', 59127, 8518, 39755, 29207, 38409, '0045 JY'], ['006-46781601', '(874)-161-4191', '051-640-9651', '015394 69728', '031-465-4208', '06-0361-7175', '084-08364651', '(081)-060-7998', '8736659091', '(0541) 297751'], ['0953-590-3053', '(546)-478-0455', '081-591-0672', '07076 491089', '081-676-9097', '0460-997-372', '0999-334-1159', '(385)-105-1148', '8433067343', '(06) 82764245'])
[2023-08-16T20:02:10.473+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.date' object has no attribute '__module__'
[2023-08-16T20:02:10.484+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=random_user_v1, task_id=extract_relevant_credentials, execution_date=20230813T000000, start_date=20230816T200210, end_date=20230816T200210
[2023-08-16T20:02:10.492+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 30 for task extract_relevant_credentials ('datetime.date' object has no attribute '__module__'; 2204)
[2023-08-16T20:02:10.512+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-16T20:02:10.533+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
