[2023-08-16T20:07:19.559+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-06T00:00:00+00:00 [queued]>
[2023-08-16T20:07:19.568+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-06T00:00:00+00:00 [queued]>
[2023-08-16T20:07:19.569+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T20:07:19.570+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 6
[2023-08-16T20:07:19.571+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T20:07:19.581+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_credentials> on 2023-08-06 00:00:00+00:00
[2023-08-16T20:07:19.588+0000] {standard_task_runner.py:55} INFO - Started process 2589 to run task
[2023-08-16T20:07:19.593+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'random_user_v1', 'extract_relevant_credentials', 'scheduled__2023-08-06T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/random_user_etl.py', '--cfg-path', '/tmp/tmpy535ko9v']
[2023-08-16T20:07:19.595+0000] {standard_task_runner.py:83} INFO - Job 47: Subtask extract_relevant_credentials
[2023-08-16T20:07:19.679+0000] {task_command.py:389} INFO - Running <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-06T00:00:00+00:00 [running]> on host c0eab1525b89
[2023-08-16T20:07:19.821+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mujjeeb
AIRFLOW_CTX_DAG_ID=random_user_v1
AIRFLOW_CTX_TASK_ID=extract_relevant_credentials
AIRFLOW_CTX_EXECUTION_DATE=2023-08-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-06T00:00:00+00:00
[2023-08-16T20:07:19.825+0000] {python.py:177} INFO - Done. Returned value was: (['زهرا', 'Claudia', 'Bureviy', 'Gordon', 'Viraj', 'Clémence', 'Christian', 'Brativoy', 'رونیکا', 'Alice'], ['مرادی', 'Giménez', 'Gucalo', 'Parker', 'Babu', 'Menard', 'Medina', 'Dmitriv', 'محمدخان', 'Davidson'], ['female', 'female', 'male', 'male', 'male', 'female', 'male', 'male', 'female', 'female'], ['zhr.mrdy@example.com', 'claudia.gimenez@example.com', 'bureviy.gucalo@example.com', 'gordon.parker@example.com', 'viraj.babu@example.com', 'clemence.menard@example.com', 'christian.medina@example.com', 'brativoy.dmitriv@example.com', 'rwnykh.mhmdkhn@example.com', 'alice.davidson@example.com'], [datetime.date(1971, 8, 10), datetime.date(1970, 6, 13), datetime.date(1986, 2, 28), datetime.date(1949, 12, 5), datetime.date(1995, 4, 16), datetime.date(1952, 12, 25), datetime.date(1987, 11, 9), datetime.date(1969, 2, 20), datetime.date(1987, 5, 21), datetime.date(1956, 10, 13)], ['Iran', 'Spain', 'Ukraine', 'United Kingdom', 'India', 'France', 'Spain', 'Ukraine', 'Iran', 'Ireland'], ['House 2671, میدان رسالت', 'House 4190, Paseo de Zorrilla', 'House 5982, Voloshkoviy provulok', 'House 5249, School Lane', 'House 7538, Rajpur Rd', "House 8696, Avenue de l'Abbé-Roussel", 'House 9729, Calle Nebrija', "House 9131, Grab'yanki", 'House 5939, شهید عباس افضلی', 'House 8816, Park Avenue'], ['تهران', 'La Palma', 'Rogatin', 'Leicester', 'Nellore', 'Argenteuil', 'Parla', 'Dovzhansk', 'کاشان', 'Gorey'], ['زنجان', 'Canarias', 'Vinnicka', 'Cleveland', 'Madhya Pradesh', 'Moselle', 'Navarra', 'Zakarpatska', 'مرکزی', 'Dublin City'], [58867, 55758, 87913, 'VD1 8BA', 10694, 65523, 56355, 57709, 88081, 40061], ['095-23704727', '923-782-765', '(066) E99-4026', '019467 42416', '7832760632', '05-26-42-47-46', '978-524-295', '(068) K30-1615', '072-84804685', '061-897-8404'], ['0935-057-0397', '600-316-538', '(098) X51-9951', '07812 336588', '8258709485', '06-77-10-83-04', '648-151-976', '(067) F38-7193', '0972-240-5337', '081-972-6254'])
[2023-08-16T20:07:19.845+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.date' object has no attribute '__module__'
[2023-08-16T20:07:19.862+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=random_user_v1, task_id=extract_relevant_credentials, execution_date=20230806T000000, start_date=20230816T200719, end_date=20230816T200719
[2023-08-16T20:07:19.877+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 47 for task extract_relevant_credentials ('datetime.date' object has no attribute '__module__'; 2589)
[2023-08-16T20:07:19.926+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-16T20:07:19.955+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
