[2023-08-16T19:57:32.041+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-09T00:00:00+00:00 [queued]>
[2023-08-16T19:57:32.055+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-09T00:00:00+00:00 [queued]>
[2023-08-16T19:57:32.056+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T19:57:32.057+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-08-16T19:57:32.059+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T19:57:32.073+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_credentials> on 2023-08-09 00:00:00+00:00
[2023-08-16T19:57:32.080+0000] {standard_task_runner.py:55} INFO - Started process 1853 to run task
[2023-08-16T19:57:32.089+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'random_user_v1', 'extract_relevant_credentials', 'scheduled__2023-08-09T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/random_user_etl.py', '--cfg-path', '/tmp/tmpaxtyx4fc']
[2023-08-16T19:57:32.093+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask extract_relevant_credentials
[2023-08-16T19:57:32.192+0000] {task_command.py:389} INFO - Running <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-09T00:00:00+00:00 [running]> on host c0eab1525b89
[2023-08-16T19:57:32.328+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mujjeeb
AIRFLOW_CTX_DAG_ID=random_user_v1
AIRFLOW_CTX_TASK_ID=extract_relevant_credentials
AIRFLOW_CTX_EXECUTION_DATE=2023-08-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-09T00:00:00+00:00
[2023-08-16T19:57:32.334+0000] {python.py:177} INFO - Done. Returned value was: (['Julia', 'Frances', 'Mélissa', 'Charles', 'یاسمن', 'Saranya', 'Iker', 'Mads', 'Lucy', 'Ralf'], ['Hanninen', 'Bishop', 'Roussel', 'Moore', 'مرادی', 'Naik', 'Guerrero', 'Pedersen', 'Mcdonalid', 'Haupt'], ['female', 'female', 'female', 'male', 'female', 'female', 'male', 'male', 'female', 'male'], ['julia.hanninen@example.com', 'frances.bishop@example.com', 'melissa.roussel@example.com', 'charles.moore@example.com', 'ysmn.mrdy@example.com', 'saranya.naik@example.com', 'iker.guerrero@example.com', 'mads.pedersen@example.com', 'lucy.mcdonalid@example.com', 'ralf.haupt@example.com'], [datetime.date(1959, 10, 16), datetime.date(1954, 3, 19), datetime.date(1982, 11, 25), datetime.date(1998, 1, 15), datetime.date(1974, 2, 23), datetime.date(1958, 4, 4), datetime.date(1998, 6, 20), datetime.date(1981, 9, 2), datetime.date(1976, 8, 14), datetime.date(1989, 3, 16)], ['Finland', 'United States', 'France', 'New Zealand', 'Iran', 'India', 'Spain', 'Denmark', 'United States', 'Germany'], ['House 6764, Hämeentie', 'House 6794, Smokey Ln', 'House 4283, Avenue Debourg', 'House 9198, Tennyson Street', 'House 1003, مقدس اردبیلی', 'House 1108, Shivajinagar', 'House 1032, Calle del Arenal', 'House 552, Rødtjørnevej', 'House 2734, Wycliff Ave', 'House 4545, Fasanenweg'], ['Kurikka', 'Coppell', 'Le Havre', 'Gisborne', 'اصفهان', 'Shimla', 'Orihuela', 'Hurup Thy', 'Waco', 'Breuberg'], ['Tavastia Proper', 'South Dakota', 'Yonne', 'Auckland', 'کرمانشاه', 'Bihar', 'Cataluña', 'Danmark', 'North Dakota', 'Saarland'], [18793, 46046, 19627, 39915, 30309, 53952, 43825, 14145, 32923, 29035], ['06-232-678', '(936) 761-0918', '03-31-23-10-57', '(424)-042-1988', '040-65411904', '9902985663', '932-573-892', '49072056', '(637) 229-3044', '0493-6311898'], ['043-318-55-30', '(245) 886-1277', '06-23-14-59-76', '(326)-951-0477', '0917-786-1796', '9888463129', '679-973-140', '49759964', '(794) 226-0211', '0173-4369494'])
[2023-08-16T19:57:32.351+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.date' object has no attribute '__module__'
[2023-08-16T19:57:32.386+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=random_user_v1, task_id=extract_relevant_credentials, execution_date=20230809T000000, start_date=20230816T195732, end_date=20230816T195732
[2023-08-16T19:57:32.402+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task extract_relevant_credentials ('datetime.date' object has no attribute '__module__'; 1853)
[2023-08-16T19:57:32.429+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-16T19:57:32.455+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
